### ISSUE TITLE
后台呢?

### ISSUE THREAD

**Issue by kunlongxu** [jiangjiu/vue-leancloud-blog#4]
一直在学Nodejs，无意中看到这个项目，赞无博主一个，挺厉害的，不过，我下了源码看了下，怎么没找到后台啊。。。

**Comment by jiangjiu** [comment]
@linmodev 后台写的很简陋就没有放出来[捂脸]可以自己写写呢

**Comment by kunlongxu** [comment]
@jiangjiu 前台写的很好了啊，不过我是想用elementui写个后台和你这个搭起来，而且我是新手不会用mongodb所以看这个leancloud真心方便，想全套做一下，博主要是可以的话麻烦把后台代码也提供一下。。

**Comment by jiangjiu** [comment]
@linmodev 如果你是指后台的node和leancloud的话，里面已经有了啊，我说的后台是指写文章进数据存储leancloud的部分，和直接改数据库没有什么区别。。。
